### ISSUE TITLE
文件占用

### ISSUE THREAD

**Issue by Sherry520** [yzhlinscau/AFEchidna#3]
林老师您好：
       echidna()在运行模型的时候，因为数据的问题，没有成功运行。我需要去修改数据文件，但是提示数据文件处于锁定状态。
如果我关闭R，提示cmd.exe应用程序错误，我必须得重启电脑才能打开数据文件。所以，是否有途径可以正常解除程序的运行，使得可以容易的去修改数据文件？
![image](https://user-images.githubusercontent.com/22561797/224947545-0db011c6-0e8c-4085-89ee-c01e28c869f2.png)

![image](https://user-images.githubusercontent.com/22561797/224947440-ab8d16c1-fc31-45c9-8ed7-25435db5e432.png)

**Comment by yzhlinscau** [comment]
如果无法关闭出错信息窗口，那就只能重启电脑。发自我的荣耀手机-------- 原始邮件 --------发件人： Yuhang Guo ***@***.***>日期： 2023年3月14日周二 16:55收件人： yzhlinscau/AFEchidna ***@***.***>抄送： Subscribed ***@***.***>主    题： [yzhlinscau/AFEchidna] 文件占用 (Issue #3)
林老师您好：
echidna()在运行模型的时候，因为数据的问题，没有成功运行。我需要去修改数据文件，但是提示数据文件处于锁定状态。
如果我关闭R，提示cmd.exe应用程序错误，我必须得重启电脑才能打开数据文件。所以，是否有途径可以正常解除程序的运行，使得可以容易的去修改数据文件？

**Comment by Sherry520** [comment]
好的，谢谢林老师。
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yuanzhen ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月14日 17:10
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Yuhang ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [yzhlinscau/AFEchidna] 文件占用 (Issue #3)
        
      
    
  

如果无法关闭出错信息窗口，那就只能重启电脑。发自我的荣耀手机-------- 原始邮件 --------发件人： Yuhang Guo ***@***.***>日期： 2023年3月14日周二 16:55收件人： yzhlinscau/AFEchidna ***@***.***>抄送： Subscribed ***@***.***>主    题： [yzhlinscau/AFEchidna] 文件占用 (Issue #3)

林老师您好：

echidna()在运行模型的时候，因为数据的问题，没有成功运行。我需要去修改数据文件，但是提示数据文件处于锁定状态。

如果我关闭R，提示cmd.exe应用程序错误，我必须得重启电脑才能打开数据文件。所以，是否有途径可以正常解除程序的运行，使得可以容易的去修改数据文件？
